---
title: "Επιπτώσεις των γραμμικών μετασχηματισμών στα μέτρα θέσης και διασποράς"
author: "Κώστας Κούδας"
cache: TRUE
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```



```{r, echo=F}
rm(list = ls())
```


<div class="alert-danger">⚠️️ΥΠΟ ΚΑΤΑΣΚΕΥΗ⚠️</div>

# Παρουσίαση αρχικών δεδομένων

```{r, echo=FALSE}
x <- rnorm(1000, mean =4, sd=1)
myDatax <- data.frame(x= x)
```


```{r echo = F, results='asis', message=FALSE}
knitr::kable(head(myDatax, n=100)) %>%
kable_styling("striped", full_width = F) %>%
scroll_box(width = "max-content", height = "200px")
```


# Προσθέσεις - αφαιρέσεις  {.tabset .tabset-fade .tabset-pills}

## Προσθέσεις

```{r, echo=FALSE}
xSYN3 <- x+3
myDataxSYN3 <- data.frame(x= x, xSYN3=xSYN3)
```


```{r echo = F, results='asis', message=FALSE}
knitr::kable(head(myDataxSYN3, n=100)) %>%
kable_styling("striped", full_width = F) %>%
scroll_box(width = "max-content", height = "200px")
```



## Αφαιρέσεις

```{r, echo=FALSE}
xPLIN1 <- x-1
myDataxPLIN1 <- data.frame(x= x, xPLIN1=xPLIN1)
```


```{r echo = F, results='asis', message=FALSE}
knitr::kable(head(myDataxPLIN1, n=100)) %>%
kable_styling("striped", full_width = F) %>%
scroll_box(width = "max-content", height = "200px")
```


# Πολλαπλασιασμοί - διαιρέσεις  {.tabset .tabset-fade .tabset-pills}

## Πολλαπλασιασμός με θετικό

```{r, echo=FALSE}
xEPI2 <- 2*x
myDataxEPI2 <- data.frame(x= x, xEPI2=xEPI2)
```


```{r echo = F, results='asis', message=FALSE}
knitr::kable(head(myDataxEPI2, n=100)) %>%
kable_styling("striped", full_width = F) %>%
scroll_box(width = "max-content", height = "200px")
```



## Διαίρεση με θετικό

```{r, echo=FALSE}
xDIA3 <- x/3
myDataxDIA3 <- data.frame(x= x, xDIA3=xDIA3)
```


```{r echo = F, results='asis', message=FALSE}
knitr::kable(head(myDataxDIA3, n=100)) %>%
kable_styling("striped", full_width = F) %>%
scroll_box(width = "max-content", height = "200px")
```


## Πολλαπλασιασμός με αρνητικό


```{r, echo=FALSE}
xEPIplin2 <- -2*x
myDataxEPIplin2 <- data.frame(x= x, xEPIplin2=xEPIplin2)
```


```{r echo = F, results='asis', message=FALSE}
knitr::kable(head(myDataxEPIplin2, n=100)) %>%
kable_styling("striped", full_width = F) %>%
scroll_box(width = "max-content", height = "200px")
```






