---
title: "Διατακτική πολυδιάστατη προσαρμογή κλίμακας"
author: "Κώστας Κούδας"
cache: TRUE
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

```{r, echo=F}
rm(list = ls())
```

# Εύρεση διάστασης

```{r, eval=FALSE}
distance <- psych::corr.test(mnd_test[,facets]) %>%
  .$r %>%
  psych::cor2dist()
```

```{r, eval=FALSE}
# Create a sample data matrix
some_data_matrix <- matrix(runif(50), ncol = 5)

# Load the vegan package
if(!require(vegan)){
  install.packages("vegan")
  library(vegan)
}

# Calculate the dissimilarity matrix
dissimilarities <- vegdist(some_data_matrix)
```



```{r, eval=FALSE}
if(!require(smacof)){
  install.packages("smacof")
  library(smacof)
}
## The for loop runs the MDS function for the amount of variables in the set - 1. 
randomstress_value <- 1:(length(some_data_matrix) - 1)
stress_values <- 1:(length(some_data_matrix) - 1)
for(ii in 1:(length(some_data_matrix) - 1)){
            distance_MDS <- smacof::mds(dissimilarities, ndim = ii,
                                        type =   "ordinal")
            randomstress <- smacof::randomstress(37, ndim = ii, nrep = 10,
                                                 type = "ordinal")
            randomstress_value[ii] <- mean(randomstress)
            stress_values[ii] <- distance_MDS$stress
}
```



# Εκτέλεση διαδικασίας διατακτικής πολυδιάστατης προσαρμογής κλίμακας


```{r, eval=FALSE}
# Perform NMDS
nmds_result <- metaMDS(dissimilarities, k = 2)

# Plot the results
plot(nmds_result, type = "n")
points(nmds_result, pch = 21, bg = "lightblue")
```


```{r, eval=FALSE}
# ΜΕΤΡΙΚΗ MDS!!!
# Load necessary libraries
library(cluster)

# Load the iris data set
data(iris)

# Perform MDS analysis
mds_iris <- cmdscale(dist(iris[, 1:4]))

# Plot the results
plot(mds_iris[, 1], mds_iris[, 2], 
     type = "n", xlab = "MDS Dimension 1", 
     ylab = "MDS Dimension 2")

# Plot the points and label them with 
# the first two letters of the species name
points(mds_iris[, 1], mds_iris[, 2], 
       pch = 21, bg = "lightblue")
text(mds_iris[, 1], mds_iris[, 2], 
     labels = substr(iris$Species, 1, 2), 
     pos = 3, cex = 0.8)

# Form clusters using K-means clustering (specify the number of clusters, e.g., 3)
kmeans_clusters <- kmeans(mds_iris, centers = 3)$cluster

# Add the cluster information to the plot
points(mds_iris[, 1], mds_iris[, 2], 
       pch = 21, bg = kmeans_clusters, cex = 1.2)
```