<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Κώστας Κούδας" />

<meta name="date" content="2025-04-02" />

<title>Διατακτική πολυδιάστατη προσαρμογή κλίμακας</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">🐈 Αρχική</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-solid fa-screwdriver-wrench"></span>
     
    Εργαλεία
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="pinakes.html">Πίνακες δεδομένων</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Περιγραφική στατιστική</a>
      <ul class="dropdown-menu" role="menu">
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Συχνότητες</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="syxnotites.html">Συχνότητες</a>
            </li>
            <li>
              <a href="pikilomorfia.html">Μέτρηση ποικιλομορφίας</a>
            </li>
            <li>
              <a href="piechart.html">Κυκλικό διάγραμμα</a>
            </li>
            <li>
              <a href="barplot.html">Ραβδόγραμμα</a>
            </li>
            <li>
              <a href="histogram.html">Ιστόγραμμα</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="metrathesis.html">Μέτρα θέσης</a>
        </li>
        <li>
          <a href="metradiasporas.html">Μέτρα διασποράς</a>
        </li>
        <li>
          <a href="asymmetria.html">Μέτρα ασυμμετρίας</a>
        </li>
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Συσχέτιση</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="metrasysxetisis.html">Μέτρα συσχέτισης</a>
            </li>
            <li class="dropdown-submenu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Προσδιορισμός συσχέτισης</a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="diagramSysxet.html">Διαγράμματα</a>
                </li>
                <li>
                  <a href="eytheiesPalindr.html">Ευθείες παλινδρόμησης</a>
                </li>
                <li>
                  <a href="kampylesPalindr.html">Καμπύλες παλινδρόμησης</a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Πιθανότητες</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="ennoiaPith.html">Η έννοια της πιθανότητας</a>
        </li>
        <li>
          <a href="ergaliaPith.html">Βασικά εργαλεία</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Εκτιμητική</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="ektimMean.html">Για μέση τιμή</a>
        </li>
        <li>
          <a href="ektimPososto.html">Για το ποσοστό</a>
        </li>
        <li>
          <a href="bootstrapMethod.html">Μέθοδος Bootstrap</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Έλεγχος υποθέσεων</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="tTest.html">t-έλεγχος για το ποσοστό</a>
        </li>
        <li>
          <a href="tTestMean.html">t-έλεγχος για τη μέση τιμή</a>
        </li>
        <li>
          <a href="zTest.html">z-έλεγχος για διαφορά ποσοστών</a>
        </li>
        <li>
          <a href="x2Test.html">χ2 έλεγχος για την ανεξαρτησία</a>
        </li>
        <li>
          <a href="anova.html">Επίδραση ενός παράγοντα</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Προσδιορισμός κατανομής</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="findDist.html">Προσδιορισμός κατανομής</a>
        </li>
        <li>
          <a href="NormTest.html">Έλεγχος κανονικότητας</a>
        </li>
        <li>
          <a href="GraphFindDist.html">Γραφικός προσδιορισμός κατανομής</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Μαρκοβιανές αλυσίδες</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="metabMarkov.html">Περιγραφή μεταβάσεων</a>
        </li>
        <li>
          <a href="metabMarkovPol.html">Μεταβάσεις σε περισσότερα βήματα</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Χρονικές σειρές</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="timeBasic.html">Βασικά εργαλεία</a>
        </li>
        <li>
          <a href="motiba.html">Μοτίβα</a>
        </li>
        <li>
          <a href="periodikotita.html">Μελέτη εποχικότητας</a>
        </li>
        <li>
          <a href="arima.html">Πρόβλεψη χρονοσειρών με μοντέλα ARIMA</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Πολυμεταβλητή ανάλυση</a>
      <ul class="dropdown-menu" role="menu">
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Περιγραφική στατιστική</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="astrogramma.html">Αστρόγραμμα</a>
            </li>
          </ul>
        </li>
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Ανάλυση συστοιχιών</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="distTree.html">Μήτρα απόστασης – δεντρόγραμμα</a>
            </li>
          </ul>
        </li>
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Πολυδιάστατη προσαρμογή κλίμακας</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="mds.html">Διατακτική πολυδιάστατη προσαρμογή κλίμακας</a>
            </li>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-solid fa-flask-vial"></span>
     
    Έρευνες
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="apoxi.html">Αποχή στις εκλογές</a>
    </li>
    <li>
      <a href="pisa.html">Εξέταση αποτελεσμάτων PISA</a>
    </li>
    <li>
      <a href="workHexitPov.html">Έξοδος από τη φτώχεια</a>
    </li>
    <li>
      <a href="gini.html">Μετρώντας την ανισότητα</a>
    </li>
    <li>
      <a href="strikes.html">Απεργιακές κινητοποιήσεις</a>
    </li>
    <li>
      <a href="spiti.html">Εξέταση τιμών ακινήτων</a>
    </li>
    <li>
      <a href="aytokinhta.html">Αξιολόγηση μεταχειρισμένων αυτοκινήτων</a>
    </li>
    <li>
      <a href="kondratiev.html">Κύματα Kondratiev</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-solid fa-mug-saucer"></span>
     
    Εντός εκτός κι επί τα αυτά
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Κατανομές</a>
      <ul class="dropdown-menu" role="menu">
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Διακριτές κατανομές</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="uniformDiscr.html">Ομοιόμορφη διακριτή κατανομή</a>
            </li>
            <li>
              <a href="binom.html">Διωνυμική κατανομή</a>
            </li>
            <li>
              <a href="hyperGeom.html">Υπεργεωμετρική κατανομή</a>
            </li>
            <li>
              <a href="geom.html">Γεωμετρική κατανομή</a>
            </li>
            <li>
              <a href="nBinom.html">Αρνητική διωνυμική κατανομή</a>
            </li>
            <li>
              <a href="poisson.html">Κατανομή Poisson</a>
            </li>
          </ul>
        </li>
        <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Συνεχείς κατανομές</a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="uniformCont.html">Ομοιόμορφη συνεχής κατανομή</a>
            </li>
            <li>
              <a href="expDist.html">Εκθετική κατανομή</a>
            </li>
            <li>
              <a href="gammaDist.html">Κατανομή Γάμμα</a>
            </li>
            <li>
              <a href="normalDist.html">Κανονική κατανομή</a>
            </li>
          </ul>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Οπλισμένοι με Mathematica</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="dataMathematica.html">Μετατροπή λίστας ή πίνακα για το Mathematica</a>
        </li>
        <li>
          <a href="exoplismoiW4SCI.html">Κούρσα εξοπλισμών</a>
        </li>
        <li>
          <a href="politicsDistW4SCI.html">Εξέλιξη κατανομής πολιτικού φάσματος</a>
        </li>
        <li>
          <a href="FrobeniusPerron.html">Ντετερμινιστικό μοντέλο από τυχαιοκρατικό</a>
        </li>
        <li>
          <a href="fuzzySocSci.html">Μοντελοποιώντας την κοινωνική διαστρωμάτωση</a>
        </li>
        <li>
          <a href="aristeradaxia.html">Εξέλιξη πολιτικών σχηματισμών</a>
        </li>
        <li>
          <a href="BlackScoles.html">Μοντέλο Black-Scoles</a>
        </li>
        <li>
          <a href="TaxikiSyneidisi.html">Ταξική συνείδηση</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Διδακτική των Στοχαστικών Μαθηματικών</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="linearSX.html">Επιπτώσεις των γραμμικών μετασχηματισμών στα μέτρα θέσης και διασποράς</a>
        </li>
      </ul>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Διατακτική πολυδιάστατη προσαρμογή
κλίμακας</h1>
<h4 class="author">Κώστας Κούδας</h4>
<h4 class="date">2025-04-02</h4>

</div>


<div id="παρουσίαση-δεδομένων" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Παρουσίαση
δεδομένων</h1>
<p>Στην ενότητα αυτή θα μελετήσουμε διάφορες χώρες ως προς κάποιους
δείκτες. Στόχος μας θα είναι να βρούμε πόσες πραγματικά παράμετροι
χρειάζονται για την περιγραφή τους και να βρούμε πώς ομαδοποιούνται
βάσει αυτών.</p>
<p>Εν προκειμένω αντλήσαμε δεδομένα από την <a
href="https://www.un-ilibrary.org/content/books/9789210452847">ετήσια
στατιστική επετηρίδα των Ηνωμένων Εθνών για το 1997</a>. Οι δείκτες
είναι:</p>
<ul>
<li><p>ο ετήσιος ποσοστιαίος ρυθμός αύξησης του πληθυσμού
(<code>ayxisi</code>),</p></li>
<li><p>το προσδόκιμο ζωής σε έτη (<code>zoi</code>),</p></li>
<li><p>το ποσοστό βρεφικής θνησιμότητας ανά 1000 γενήσεις
(<code>pbth</code>),</p></li>
<li><p>το συνολικό ποσοστό γονιμότητας (<code>spg</code>) και</p></li>
<li><p>το ακαθάριστο κατά κεφαλή εγχώριο προϊόν σε δολάρια ΗΠΑ
(<code>aep</code>),</p></li>
</ul>
<p>οι οποίοι παρουσιάζονται στον κάτωθι πίνακα (βλ. <a
href="https://kkoudas01.github.io/r4social/pinakes.html#12_%CE%9A%CE%B1%CF%84%CE%B1%CF%83%CE%BA%CE%B5%CF%85%CE%AE_%CE%BB%CE%AF%CF%83%CF%84%CE%B1%CF%82_%CE%AE_%CF%80%CE%AF%CE%BD%CE%B1%CE%BA%CE%B1_%CF%84%CE%B9%CE%BC%CF%8E%CE%BD_%CF%83%CF%84%CE%B7%CE%BD_R">επίσης</a>).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>xora <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ALB&quot;</span>,<span class="st">&quot;ARG&quot;</span>,<span class="st">&quot;AUS&quot;</span>,<span class="st">&quot;AUST&quot;</span>,<span class="st">&quot;BJ&quot;</span>,<span class="st">&quot;BOL&quot;</span>,<span class="st">&quot;BRA&quot;</span>,<span class="st">&quot;CH&quot;</span>,<span class="st">&quot;CN&quot;</span>,<span class="st">&quot;COL&quot;</span>,<span class="st">&quot;HR&quot;</span>,<span class="st">&quot;SLV&quot;</span>,<span class="st">&quot;FR&quot;</span>,<span class="st">&quot;GR&quot;</span>,<span class="st">&quot;GT&quot;</span>,<span class="st">&quot;IR&quot;</span>,<span class="st">&quot;IT&quot;</span>,<span class="st">&quot;MW&quot;</span>,<span class="st">&quot;NL&quot;</span>,<span class="st">&quot;PK&quot;</span>,<span class="st">&quot;PG&quot;</span>,<span class="st">&quot;PE&quot;</span>,<span class="st">&quot;RO&quot;</span>,<span class="st">&quot;USA&quot;</span>,<span class="st">&quot;ZW&quot;</span>)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>ayxisi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.2</span>,<span class="fl">1.2</span>,<span class="fl">1.1</span>,<span class="dv">1</span>,<span class="fl">3.2</span>,<span class="fl">2.4</span>,<span class="fl">1.5</span>,<span class="fl">2.8</span>,<span class="fl">1.1</span>,<span class="fl">1.7</span>,<span class="sc">-</span><span class="fl">1.5</span>,<span class="fl">2.2</span>,<span class="fl">0.4</span>,<span class="fl">0.6</span>,<span class="fl">2.9</span>,<span class="fl">2.3</span>,<span class="sc">-</span><span class="fl">0.2</span>,<span class="fl">3.3</span>,<span class="fl">0.7</span>,<span class="fl">3.1</span>,<span class="fl">1.9</span>,<span class="fl">1.7</span>,<span class="sc">-</span><span class="fl">0.5</span>,<span class="fl">1.1</span>,<span class="fl">4.4</span>)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>zoi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">69.2</span>,<span class="fl">68.6</span>,<span class="fl">74.7</span>,<span class="dv">73</span>,<span class="fl">45.9</span>,<span class="fl">57.7</span>,<span class="dv">64</span>,<span class="fl">50.1</span>,<span class="fl">66.7</span>,<span class="fl">66.4</span>,<span class="fl">67.1</span>,<span class="fl">63.9</span>,<span class="dv">73</span>,<span class="dv">75</span>,<span class="fl">62.4</span>,<span class="dv">67</span>,<span class="fl">74.2</span>,<span class="dv">45</span>,<span class="fl">74.4</span>,<span class="fl">60.6</span>,<span class="fl">55.2</span>,<span class="fl">64.1</span>,<span class="fl">66.6</span>,<span class="fl">72.5</span>,<span class="fl">52.4</span>)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>pbth <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">24</span>,<span class="dv">7</span>,<span class="dv">7</span>,<span class="dv">86</span>,<span class="dv">75</span>,<span class="dv">58</span>,<span class="dv">116</span>,<span class="dv">44</span>,<span class="dv">37</span>,<span class="dv">9</span>,<span class="dv">46</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">48</span>,<span class="dv">36</span>,<span class="dv">8</span>,<span class="dv">143</span>,<span class="dv">7</span>,<span class="dv">91</span>,<span class="dv">68</span>,<span class="dv">64</span>,<span class="dv">23</span>,<span class="dv">9</span>,<span class="dv">67</span>)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a>spg <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.9</span>,<span class="fl">2.8</span>,<span class="fl">1.9</span>,<span class="fl">1.5</span>,<span class="fl">7.1</span>,<span class="fl">4.8</span>,<span class="fl">2.9</span>,<span class="fl">5.3</span>,<span class="dv">2</span>,<span class="fl">2.7</span>,<span class="fl">1.7</span>,<span class="dv">4</span>,<span class="fl">1.7</span>,<span class="fl">1.4</span>,<span class="fl">5.4</span>,<span class="dv">5</span>,<span class="fl">1.3</span>,<span class="fl">7.2</span>,<span class="fl">1.6</span>,<span class="fl">6.2</span>,<span class="fl">5.1</span>,<span class="fl">3.4</span>,<span class="fl">1.5</span>,<span class="fl">2.1</span>,<span class="dv">5</span>)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a>aep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">659.91</span>,<span class="fl">4343.04</span>,<span class="fl">17529.98</span>,<span class="fl">20561.88</span>,<span class="fl">398.21</span>,<span class="fl">812.19</span>,<span class="fl">3219.22</span>,<span class="fl">97.39</span>,<span class="fl">341.31</span>,<span class="fl">1246.87</span>,<span class="fl">5400.66</span>,<span class="fl">988.58</span>,<span class="fl">21076.77</span>,<span class="fl">6501.23</span>,<span class="fl">831.81</span>,<span class="fl">9129.34</span>,<span class="fl">19204.92</span>,<span class="fl">229.01</span>,<span class="fl">18961.9</span>,<span class="fl">385.59</span>,<span class="fl">839.03</span>,<span class="fl">1674.15</span>,<span class="fl">1647.97</span>,<span class="fl">21965.08</span>,<span class="fl">686.75</span>)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a>deimografikoiDeiktes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">XORA=</span>xora, <span class="at">ayxisi=</span>ayxisi, <span class="at">Zoi=</span>zoi, <span class="at">PBTH=</span>pbth, <span class="at">SPG=</span>spg, <span class="at">AEP=</span>aep)</span></code></pre></div>
<div
style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:200px; overflow-x: scroll; width:max-content; ">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
XORA
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
ayxisi
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Zoi
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PBTH
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPG
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AEP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ALB
</td>
<td style="text-align:right;">
1.2
</td>
<td style="text-align:right;">
69.2
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
659.91
</td>
</tr>
<tr>
<td style="text-align:left;">
ARG
</td>
<td style="text-align:right;">
1.2
</td>
<td style="text-align:right;">
68.6
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
2.8
</td>
<td style="text-align:right;">
4343.04
</td>
</tr>
<tr>
<td style="text-align:left;">
AUS
</td>
<td style="text-align:right;">
1.1
</td>
<td style="text-align:right;">
74.7
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1.9
</td>
<td style="text-align:right;">
17529.98
</td>
</tr>
<tr>
<td style="text-align:left;">
AUST
</td>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:right;">
73.0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1.5
</td>
<td style="text-align:right;">
20561.88
</td>
</tr>
<tr>
<td style="text-align:left;">
BJ
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
45.9
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
7.1
</td>
<td style="text-align:right;">
398.21
</td>
</tr>
<tr>
<td style="text-align:left;">
BOL
</td>
<td style="text-align:right;">
2.4
</td>
<td style="text-align:right;">
57.7
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
812.19
</td>
</tr>
<tr>
<td style="text-align:left;">
BRA
</td>
<td style="text-align:right;">
1.5
</td>
<td style="text-align:right;">
64.0
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
3219.22
</td>
</tr>
<tr>
<td style="text-align:left;">
CH
</td>
<td style="text-align:right;">
2.8
</td>
<td style="text-align:right;">
50.1
</td>
<td style="text-align:right;">
116
</td>
<td style="text-align:right;">
5.3
</td>
<td style="text-align:right;">
97.39
</td>
</tr>
<tr>
<td style="text-align:left;">
CN
</td>
<td style="text-align:right;">
1.1
</td>
<td style="text-align:right;">
66.7
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
341.31
</td>
</tr>
<tr>
<td style="text-align:left;">
COL
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
66.4
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
2.7
</td>
<td style="text-align:right;">
1246.87
</td>
</tr>
<tr>
<td style="text-align:left;">
HR
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
67.1
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
5400.66
</td>
</tr>
<tr>
<td style="text-align:left;">
SLV
</td>
<td style="text-align:right;">
2.2
</td>
<td style="text-align:right;">
63.9
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
988.58
</td>
</tr>
<tr>
<td style="text-align:left;">
FR
</td>
<td style="text-align:right;">
0.4
</td>
<td style="text-align:right;">
73.0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
21076.77
</td>
</tr>
<tr>
<td style="text-align:left;">
GR
</td>
<td style="text-align:right;">
0.6
</td>
<td style="text-align:right;">
75.0
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
6501.23
</td>
</tr>
<tr>
<td style="text-align:left;">
GT
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
62.4
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
5.4
</td>
<td style="text-align:right;">
831.81
</td>
</tr>
<tr>
<td style="text-align:left;">
IR
</td>
<td style="text-align:right;">
2.3
</td>
<td style="text-align:right;">
67.0
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
9129.34
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:right;">
-0.2
</td>
<td style="text-align:right;">
74.2
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
1.3
</td>
<td style="text-align:right;">
19204.92
</td>
</tr>
<tr>
<td style="text-align:left;">
MW
</td>
<td style="text-align:right;">
3.3
</td>
<td style="text-align:right;">
45.0
</td>
<td style="text-align:right;">
143
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
229.01
</td>
</tr>
<tr>
<td style="text-align:left;">
NL
</td>
<td style="text-align:right;">
0.7
</td>
<td style="text-align:right;">
74.4
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
18961.90
</td>
</tr>
<tr>
<td style="text-align:left;">
PK
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
60.6
</td>
<td style="text-align:right;">
91
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
385.59
</td>
</tr>
<tr>
<td style="text-align:left;">
PG
</td>
<td style="text-align:right;">
1.9
</td>
<td style="text-align:right;">
55.2
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
5.1
</td>
<td style="text-align:right;">
839.03
</td>
</tr>
<tr>
<td style="text-align:left;">
PE
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
64.1
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
3.4
</td>
<td style="text-align:right;">
1674.15
</td>
</tr>
<tr>
<td style="text-align:left;">
RO
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
66.6
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
1.5
</td>
<td style="text-align:right;">
1647.97
</td>
</tr>
<tr>
<td style="text-align:left;">
USA
</td>
<td style="text-align:right;">
1.1
</td>
<td style="text-align:right;">
72.5
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
2.1
</td>
<td style="text-align:right;">
21965.08
</td>
</tr>
<tr>
<td style="text-align:left;">
ZW
</td>
<td style="text-align:right;">
4.4
</td>
<td style="text-align:right;">
52.4
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
686.75
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="εύρεση-διάστασης---έντασης" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Εύρεση διάστασης -
έντασης</h1>
<p>Κάθε χώρα αναπαρίσταται από πέντε αριθμούς. Π.χ. η Αλβανία
(<code>ALB</code>) αναπαρίσταται από την πεντάδα: <strong>1.2</strong>,
<strong>69.2</strong>, <strong>30</strong>, <strong>2.9</strong>,
<strong>659.91</strong>. Είναι όμως αναγκαία η χρήση πέντε παραμέτρων;
Μήπως αυτοί οι πέντε δείκτες μπορούν να συνοψιστούν από, λόγου χάρη, δύο
δείκτες ή και έναν; Αυτό ακριβώς θα εξετάσουμε τώρα.</p>
<p>Καθόσον κάθε χώρα αντιπροσωπεύεται από μια πεντάδα αριθμών, μπορούμε
να ορίσουμε την απόσταση δύο χωρών ως την απόσταση δύο τέτοιων
πεντάδων<a href="#fn1" class="footnote-ref"
id="fnref1"><sup>1</sup></a>. Μελετώντας τις αποστάσεις αυτές μπορούμε
να δούμε αν οι χώρες μπορούν να αναπαρασταθούν με λιγότερες παραμέτρους
από πέντε. Δηλαδή ενδέχεται αυτές οι αποστάσεις να περιγράφουν
αποστάσεις σημείων πάνω σε μια ευθεία γραμμή, οπότε να απαιτείται η τιμή
μόνο μίας παραμέτρου για τον προσδιορισμό κάθε χώρας. Από την άλλη
ενδέχεται αυτές οι αποστάσεις να περιγράφουν αποστάσεις σημείων πάνω σε
ένα επίπεδο, οπότε να απαιτούνται οι τιμές δύο παραμέτρων για τον
προσδιορισμό κάθε χώρας.</p>
<p>Φυσικά, δεν περιμένουμε τα σημεία-χώρες να βρίσκονται όλα ακριβώς
πάνω σ’ ένα επίπεδο. Πάνω-κάτω εννοούμε. Στο περίπου. Με μια σχετική
ακρίβεια. Έτσι με μια σχετική ακρίβεια κείτονται όλες οι χώρες-σημεία
πάνω σε μια ευθεία, με μια άλλη σχετική ακρίβεια κείτονται όλες οι
χώρες-σημεία πάνω σε ένα επίπεδο κ.τ.λ. Εννοείται πως τη μέγιστη
ακρίβεια εν προκειμένω την έχουμε όταν θεωρούμε πως οι χώρες-σημεία
βρίσκονται σ’ ένα χώρο 5 διαστάσεων, τον χώρο των παραμέτρων
<code>ayxisi</code>, <code>zoi</code>, <code>pbth</code>,
<code>spg</code> και <code>aep</code>.</p>
<p>Εμείς όμως δεν επιδιώκουμε την απόλυτη ακρίβεια, η οποία μπορεί ήδη
να είναι θύμα τυχαίων παρεμβολών, ανακριβειών των μετρήσεων κ.τ.λ.
Επιδιώκουμε να βγάλουμε συμπυκνωμένα νοήματα με μια αποδεκτή (όχι
άπειρη) ακρίβεια. Αυτό το μέγεθος ακριβείας το αποκαλούμε <mark>ένταση
του Kruskal</mark>. Με άλλα λόγια, περιορίζοντας τις παραμέτρους από 5
σε π.χ. 2 οι αποστάσεις μεταξύ των χωρών-σημείων αλλάζουν. Το μέτρο
καλής προσαρμογής είναι η ένταση. Ακολουθεί μια ενδεικτική λίστα περί
του πώς ερμηνεύουμε τις εκάστοτε εντάσεις:</p>
<ul>
<li><p>Αν, διαλέγοντας κάποιο πλήθος παραμέτρων, η ένταση προκύψει
μικρότερη από 0.05, τότε αυτό το πλήθος αποτελεί εξαιρετικό τρόπο
αναπαράστασης.</p></li>
<li><p>Αν, διαλέγοντας κάποιο πλήθος παραμέτρων, η ένταση προκύψει 0.05,
0.06, 0.07, 0.08 ή 0.09, τότε αυτό το πλήθος αποτελεί καλή επιλογή χωρίς
πραγματικό κίνδυνο εξαγωγής εσφαλμένων συμπερασμάτων.</p></li>
<li><p>Αν, διαλέγοντας κάποιο πλήθος παραμέτρων, η ένταση προκύψει 0.10,
0.11, 0.12, 0.13, … , 0.19 τότε αυτό το πλήθος μπορεί να είναι χρήσιμο,
αλλά έχει τη δυνατότητα να παραπλανήσει. Ειδικότερα, δεν πρέπει να δοθεί
μεγάλη έμφαση στις λεπτομέρειες.</p></li>
<li><p>Αν, διαλέγοντας κάποιο πλήθος παραμέτρων, η ένταση προκύψει 0.20,
0.21, 0.22, 0.23, … , 0.34 τότε αυτό το πλήθος θα μπορούσε να είναι
επικίνδυνο να ερμηνευτεί. Έχουμε κακή προσαρμογή.</p></li>
<li><p>Αν, διαλέγοντας κάποιο πλήθος παραμέτρων, η ένταση προκύψει πάνω
από 0.35 τότε αυτό το πλήθος δεν είναι καθόλου κατάλληλο. Έχουμε κάκιστη
προσαρμογή.</p></li>
</ul>
<p>Πάμε πίσω στα δεδομένα μας! Για να απαντήσουμε τα παραπάνω ερωτήματα
θα χρησιμοποιήσουμε τη συνάρτηση
<code>eyresiDiastasis(📝📝📝, entasi = 🧗🧗🧗, ar_epan=🎼🎼🎼, metriki = 📐📐📐)</code>.
Ακολουθεί η περιγραφή των συμβόλων:</p>
<ul>
<li><p>Στη θέση του <code>📝📝📝</code> γράφουμε τον πίνακα δεδομένων
μας, εν προκειμένω το <code>deimografikoiDeiktes</code>. Εδώ θα πρέπει
να προσέξουμε ο πίνακας να είναι σε παρόμοια μορφή με τον
<code>deimografikoiDeiktes</code>. Δηλαδή η πρώτη στήλη να έχει τα
αντικείμενα που θέλουμε να μελετήσουμε και κάθε γραμμή να είναι οι τιμές
που περιγράφουν το κάθε αντικείμενο.</p></li>
<li><p>Στη θέση του <code>🧗🧗🧗</code> πάει η ένταση κάτω από την οποία
επιδιώκουμε να βρεθούμε. Κοντολογίς τον βαθμό ακριβείας. Αν αφήσουμε
κενό το κομμάτι <code>entasi = 🧗🧗🧗</code>, τότε συμπληρώνεται
αυτόματα το 0.05.</p></li>
<li><p>Η διαδικασία με την οποία λειτουργεί η συνάρτηση
<code>eyresiDiastasis()</code> είναι δοκιμής-επαλήθευσης-επανάληψης. Στη
θέση του <code>🎼🎼🎼</code> μπορούμε να βάλουμε το πλήθος των δοκιμών
που θέλουμε να γίνει. Αν αφήσουμε κενή την επιλογή
<code>ar_epan=🎼🎼🎼</code>, συμπληρώνεται αυτομάτως το 500.</p></li>
<li><p>Τέλος στη θέση του <code>📐📐📐</code> συμπληρώνουμε τη μετρική
που θέλουμε να χρησιμοποιηθεί για τον υπολογισμό των αποστάσεων. Η
προκαθορισμένη είναι η ευκλείδεια (<code>"euclidean"</code>), αλλά
μπορούμε να επιλέξουμε μία από τις <code>"manhattan"</code>,
<code>"gower"</code>, <code>"altGower"</code>, <code>"canberra"</code>,
<code>"clark"</code>, <code>"bray"</code>, <code>"kulczynski"</code>,
<code>"morisita"</code>, <code>"horn"</code>, <code>"binomial"</code>
και <code>"cao"</code>.</p></li>
</ul>
<p>Για να κατασκευαστεί η συνάρτηση <code>eyresiDiastasis()</code> θα
χρειαστούμε το πακέτο <code>vegan</code> το οποίο και εγκαθιστούμε.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(vegan)){</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;vegan&quot;</span>)</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>  <span class="fu">library</span>(vegan)</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>}</span></code></pre></div>
<p>Έτοιμοι λοιπόν για την συνάρτησή μας:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>eyresiDiastasis <span class="ot">&lt;-</span> <span class="cf">function</span>(dedomena, <span class="at">entasi =</span> <span class="fl">0.05</span>, <span class="at">ar_epan=</span><span class="dv">500</span>, <span class="at">metriki =</span> <span class="st">&quot;euclidean&quot;</span>){</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>  dedomenaS <span class="ot">&lt;-</span> <span class="fu">scale</span>(dedomena[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>  dissimilarities <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(dedomenaS,metriki)</span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>  k0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>  nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a>  stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a>  <span class="cf">while</span> (k0 <span class="sc">&lt;</span> <span class="fu">length</span>(deimografikoiDeiktes[<span class="dv">1</span>,]) <span class="sc">&amp;&amp;</span> entasi<span class="sc">&lt;</span>stress0) {</span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a>    k0 <span class="ot">&lt;-</span> k0<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb3-9"><a href="#cb3-9" tabindex="-1"></a>    nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-10"><a href="#cb3-10" tabindex="-1"></a>    stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb3-11"><a href="#cb3-11" tabindex="-1"></a>  }</span>
<span id="cb3-12"><a href="#cb3-12" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Η διάσταση είναι&quot;</span>,k0,<span class="st">&quot;και η ένταση είναι &quot;</span>,stress0,<span class="st">&quot;.&quot;</span>))</span>
<span id="cb3-13"><a href="#cb3-13" tabindex="-1"></a>  <span class="fu">stressplot</span>(nmds_result)</span>
<span id="cb3-14"><a href="#cb3-14" tabindex="-1"></a>}</span></code></pre></div>
<p>Έτσι, εκτελώντας την παρακάτω εντολή έχουμε τον απαιτούμενο αριθμό
διαστάσεων για να έχουμε εξαιρετική ακρίβεια προσαρμογής.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">eyresiDiastasis</span>(deimografikoiDeiktes)</span></code></pre></div>
<pre><code>## [1] &quot;Η διάσταση είναι 2 και η ένταση είναι  0.0248713194718483 .&quot;</code></pre>
<p><img src="mds_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Το γράφημα που προκύπτει είναι το γράφημα των αποστάσεων. Πρακτικά
είναι ένα διάγραμμα διασποράς, όπου συσχετίζει τις πραγματικές
αποστάσεις με αυτές που προκύπτουν από την μείωση της διάστασης.</p>
<p>Κάποιος, όμως, μπορεί να μην καλύπτεται με την ακρίβεια προσαρμογής
της τάξης του 0.05. Μπορεί να θέλει ακρίβεια μεγαλύτερη, δηλαδή
μικρότερη ένταση. Πόσες θα πρέπει να ήταν οι απαιτούμενες διαστάσεις, αν
θέλαμε να έχουμε ένταση π.χ. 0.02. Αυτό έρχεται να μας απαντήσει η
κάτωθι εντολή.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">eyresiDiastasis</span>(deimografikoiDeiktes, <span class="at">entasi=</span><span class="fl">0.02</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Η διάσταση είναι 3 και η ένταση είναι  0.0124986409620639 .&quot;</code></pre>
<p><img src="mds_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Παρατηρούμε ότι υπάρχει μεγαλύτερη ταύτιση θεωρητικών και
παρατηρούμενων αποστάσεων, όπερ αναμενόμενο, αφού επιλέξαμε ένταση πιο
μικρή από πριν.</p>
<p>Κάποιες φορές μπορεί να χρειαστεί να πάρουμε ανάποδα το πράγμα.
Μπορεί να έχουμε έναν επιθυμητό αριθμό διαστάσεων-παραμέτρων και να
θέλουμε να δούμε πόσο καλά προσαρμόζονται τα δεδομένα μας σ’ αυτό το
πλήθος διαστάσεων. Σε αυτό θα μας βοηθήσει η συνάρτηση
<code>eyresiEntasis(📝📝📝, diastasi =🎭🎭🎭, ar_epan=🎼🎼🎼, metriki = 📐📐📐)</code>.
Ακολουθεί η περιγραφή των συμβόλων:</p>
<ul>
<li><p>Στη θέση του <code>📝📝📝</code> γράφουμε τον πίνακα δεδομένων
μας, εν προκειμένω το <code>deimografikoiDeiktes</code>. Εδώ θα πρέπει
να προσέξουμε ο πίνακας να είναι σε παρόμοια μορφή με τον
<code>deimografikoiDeiktes</code>. Δηλαδή η πρώτη στήλη να έχει τα
αντικείμενα που θέλουμε να μελετήσουμε και κάθε γραμμή να είναι οι τιμές
που περιγράφουν το κάθε αντικείμενο.</p></li>
<li><p>Στη θέση του <code>🎭🎭🎭</code> γράφουμε το πλήθος των
παραμέτρων που θέλουμε να εξετάσουμε ως προς την ένταση. Μπορούμε να
αφήσουμε κενό το κομμάτι <code>diastasi =🎭🎭🎭</code>, οπότε
συμπληρώνεται αυτόματα το 2.</p></li>
<li><p>Η διαδικασία με την οποία λειτουργεί η συνάρτηση
<code>eyresiDiastasis()</code> είναι δοκιμής-επαλήθευσης-επανάληψης. Στη
θέση του <code>🎼🎼🎼</code> μπορούμε να βάλουμε το πλήθος των δοκιμών
που θέλουμε να γίνει. Αν αφήσουμε κενή την επιλογή
<code>ar_epan=🎼🎼🎼</code>, συμπληρώνεται αυτομάτως το 500.</p></li>
<li><p>Τέλος στη θέση του <code>📐📐📐</code> συμπληρώνουμε τη μετρική
που θέλουμε να χρησιμοποιηθεί για τον υπολογισμό των αποστάσεων. Η
προκαθορισμένη είναι η ευκλείδεια (<code>"euclidean"</code>), αλλά
μπορούμε να επιλέξουμε μία από τις <code>"manhattan"</code>,
<code>"gower"</code>, <code>"altGower"</code>, <code>"canberra"</code>,
<code>"clark"</code>, <code>"bray"</code>, <code>"kulczynski"</code>,
<code>"morisita"</code>, <code>"horn"</code>, <code>"binomial"</code>
και <code>"cao"</code>.</p></li>
</ul>
<p>Ιδού η συνάρτησή μας:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>eyresiEntasis <span class="ot">&lt;-</span> <span class="cf">function</span>(dedomena, <span class="at">diastasi =</span> <span class="dv">2</span>, <span class="at">ar_epan=</span><span class="dv">500</span>, <span class="at">metriki =</span> <span class="st">&quot;euclidean&quot;</span>){</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>  dedomenaS <span class="ot">&lt;-</span> <span class="fu">scale</span>(dedomena[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>  dissimilarities <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(dedomenaS,metriki)</span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>  k0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>  nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>  stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>  <span class="cf">while</span> (k0 <span class="sc">&lt;</span> <span class="fu">min</span>(diastasi,<span class="fu">length</span>(deimografikoiDeiktes[<span class="dv">1</span>,]))) {</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>    k0 <span class="ot">&lt;-</span> k0<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a>    nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a>    stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb8-11"><a href="#cb8-11" tabindex="-1"></a>  }</span>
<span id="cb8-12"><a href="#cb8-12" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Η διάσταση είναι&quot;</span>,k0,<span class="st">&quot;και η ένταση είναι &quot;</span>,stress0,<span class="st">&quot;.&quot;</span>))</span>
<span id="cb8-13"><a href="#cb8-13" tabindex="-1"></a>  <span class="fu">stressplot</span>(nmds_result)</span>
<span id="cb8-14"><a href="#cb8-14" tabindex="-1"></a>}</span></code></pre></div>
<p>Εκτελώντας την κάτωθι εντολή βρίσκουμε πόσο βαθμό ακρίβειας θα έχουμε
αν διαλέξουμε δύο μόνο παραμέτρους για να περιγράφουν την κατανομή των
χωρών μας.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">eyresiEntasis</span>(deimografikoiDeiktes)</span></code></pre></div>
<pre><code>## [1] &quot;Η διάσταση είναι 2 και η ένταση είναι  0.0248713193671372 .&quot;</code></pre>
<p><img src="mds_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Τι γίνεται, όμως, αν επιδιώξουμε να κατατάξουμε τις χώρες σε μια
ευθεία αριθμογραμμή; Φτάνει μια παράμετρος για να κατατάξει τις χώρες
μας;</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">eyresiEntasis</span>(deimografikoiDeiktes, <span class="at">diastasi =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Η διάσταση είναι 1 και η ένταση είναι  0.117045035019002 .&quot;</code></pre>
<p><img src="mds_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Βλέπουμε ότι προκύπτει ένταση 0.117045035019002, όπερ υποδηλώνει
ενδεχομένως παραπλανητική επάρκεια της μίας διάστασης, κάτι που φαίνεται
και από το διάγραμμα, όπου οι προσαρμοσμένες-θεωρητικές αποστάσεις
φαίνεται να έχουν έντονες αποκλίσεις από τις πραγματικές.</p>
</div>
<div id="γραφική-αναπαράσταση" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Γραφική
αναπαράσταση</h1>
<p>Το ενδιαφέρον της μεθόδου δεν σταματά εδώ. Στην περίπτωση που
προκύψουν 2 ή 3 διαστάσεις-παράμετροι μπορούμε να απεικονίσουμε τα
δεδομένα μας σε ένα αντίστοιχο γράφημα. Για την περίπτωση που θέλουμε να
δουλέψουμε και με τρισδιάστατα γραφήματα θα χρειαστούμε το πακέτο
<code>vegan3d</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(vegan3d)){</span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;vegan3d&quot;</span>)</span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>  <span class="fu">library</span>(vegan3d)</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>}</span></code></pre></div>
<p>Για να μην μακρηγορούμε, η συνάρτησή μας είναι η
<code>PoPrKlim(📝📝📝, diastasi =🎭🎭🎭, ar_epan=🎼🎼🎼, metriki = 📐📐📐)</code>.
Ακολουθεί η περιγραφή των συμβόλων:</p>
<ul>
<li><p>Στη θέση του <code>📝📝📝</code> γράφουμε τον πίνακα δεδομένων
μας, εν προκειμένω το <code>deimografikoiDeiktes</code>. Εδώ θα πρέπει
να προσέξουμε ο πίνακας να είναι σε παρόμοια μορφή με τον
<code>deimografikoiDeiktes</code>. Δηλαδή η πρώτη στήλη να έχει τα
αντικείμενα που θέλουμε να μελετήσουμε και κάθε γραμμή να είναι οι τιμές
που περιγράφουν το κάθε αντικείμενο.</p></li>
<li><p>Στη θέση του <code>🎭🎭🎭</code> γράφουμε το πλήθος των
διαστάσεων. Μπορούμε να αφήσουμε κενό το κομμάτι
<code>diastasi =🎭🎭🎭</code>, οπότε συμπληρώνεται αυτόματα το
2.</p></li>
<li><p>Η διαδικασία με την οποία λειτουργεί η συνάρτηση
<code>eyresiDiastasis()</code> είναι δοκιμής-επαλήθευσης-επανάληψης. Στη
θέση του <code>🎼🎼🎼</code> μπορούμε να βάλουμε το πλήθος των δοκιμών
που θέλουμε να γίνει. Αν αφήσουμε κενή την επιλογή
<code>ar_epan=🎼🎼🎼</code>, συμπληρώνεται αυτομάτως το 500.</p></li>
<li><p>Τέλος στη θέση του <code>📐📐📐</code> συμπληρώνουμε τη μετρική
που θέλουμε να χρησιμοποιηθεί για τον υπολογισμό των αποστάσεων. Η
προκαθορισμένη είναι η ευκλείδεια (<code>"euclidean"</code>), αλλά
μπορούμε να επιλέξουμε μία από τις <code>"manhattan"</code>,
<code>"gower"</code>, <code>"altGower"</code>, <code>"canberra"</code>,
<code>"clark"</code>, <code>"bray"</code>, <code>"kulczynski"</code>,
<code>"morisita"</code>, <code>"horn"</code>, <code>"binomial"</code>
και <code>"cao"</code>.</p></li>
</ul>
<p>Ορίστε η συνάρτησή μας:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>PoPrKlim <span class="ot">&lt;-</span> <span class="cf">function</span>(dedomena, <span class="at">diastasi =</span> <span class="dv">2</span>, <span class="at">ar_epan=</span><span class="dv">500</span>, <span class="at">metriki =</span> <span class="st">&quot;euclidean&quot;</span>){</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>  dedomenaS <span class="ot">&lt;-</span> <span class="fu">scale</span>(dedomena[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>  dissimilarities <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(dedomenaS,metriki)</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>  nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> diastasi, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>  <span class="cf">if</span> (diastasi <span class="sc">==</span> <span class="dv">2</span>){</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>  <span class="fu">ordiplot</span>(nmds_result, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>  <span class="fu">points</span>(nmds_result<span class="sc">$</span>points, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>)</span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>  <span class="fu">text</span>(nmds_result<span class="sc">$</span>points, <span class="at">labels =</span> dedomena[,<span class="dv">1</span>], <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (diastasi <span class="sc">==</span> <span class="dv">3</span>) {</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>    <span class="fu">ordiplot3d</span>(nmds_result, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>    <span class="fu">points</span>(nmds_result<span class="sc">$</span>points, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>)</span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>    <span class="fu">text</span>(nmds_result<span class="sc">$</span>points, <span class="at">labels =</span> dedomena[,<span class="dv">1</span>], <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>  }</span>
<span id="cb14-14"><a href="#cb14-14" tabindex="-1"></a>}</span></code></pre></div>
<p>Εκτελώντας, λοιπόν, την παρακάτω εντολή έχουμε την προκαθορισμένη
δισδιάστατη απεικόνιση των χωρών.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="fu">PoPrKlim</span>(deimografikoiDeiktes)</span></code></pre></div>
<p><img src="mds_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Από την άλλη, κάποιος που θα ήθελε να απεικονίσει τις χώρες μας σε
ένα τρισδιάστατο σύστημα συντεταγμένων, μπορεί να εκτελέσει τα
κάτωθι:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">PoPrKlim</span>(deimografikoiDeiktes, <span class="at">diastasi =</span> <span class="dv">3</span>)</span></code></pre></div>
<p><img src="mds_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Βεβαίως, όπως είδαμε και στην προηγούμενη ενότητα, οι δύο διαστάσεις
είναι υπεραρκετές.</p>
<p>Ένα ερώτημα που ίσως έχει απασχολήσει από πριν τον αναγνώστη είναι
«Και ποιοι είναι οι παράμετροι <code>NMDS1</code> και <code>NMDS2</code>
οι οποίοι περιγράφουν τις χώρες μας;». Αυτό η παρούσα ανάλυση δεν μπορεί
να το απαντήσει. Ίσως να είναι δύο εκ των <code>ayxisi</code>,
<code>zoi</code>, <code>pbth</code>, <code>spg</code> και
<code>aep</code>. Ίσως να είναι δύο συνδυασμοί αυτών. Ίσως και να είναι
δύο τελείως καινούριες παράμετροι, οι οποίες απλά να συνεπιρεάζουν τους
παράγοντες <code>ayxisi</code>, <code>zoi</code>, <code>pbth</code>,
<code>spg</code> και <code>aep</code>. Η απάντηση σε αυτή την ερώτηση
σίγουρα θέλει παραπάνω δουλειά από αυτόν τον μικρό κώδικα.</p>
<p>Συνολικά ο κώδικας που γράψαμε είναι ο εξής:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>xora <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ALB&quot;</span>,<span class="st">&quot;ARG&quot;</span>,<span class="st">&quot;AUS&quot;</span>,<span class="st">&quot;AUST&quot;</span>,<span class="st">&quot;BJ&quot;</span>,<span class="st">&quot;BOL&quot;</span>,<span class="st">&quot;BRA&quot;</span>,<span class="st">&quot;CH&quot;</span>,<span class="st">&quot;CN&quot;</span>,<span class="st">&quot;COL&quot;</span>,<span class="st">&quot;HR&quot;</span>,<span class="st">&quot;SLV&quot;</span>,<span class="st">&quot;FR&quot;</span>,<span class="st">&quot;GR&quot;</span>,<span class="st">&quot;GT&quot;</span>,<span class="st">&quot;IR&quot;</span>,<span class="st">&quot;IT&quot;</span>,<span class="st">&quot;MW&quot;</span>,<span class="st">&quot;NL&quot;</span>,<span class="st">&quot;PK&quot;</span>,<span class="st">&quot;PG&quot;</span>,<span class="st">&quot;PE&quot;</span>,<span class="st">&quot;RO&quot;</span>,<span class="st">&quot;USA&quot;</span>,<span class="st">&quot;ZW&quot;</span>)</span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>ayxisi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.2</span>,<span class="fl">1.2</span>,<span class="fl">1.1</span>,<span class="dv">1</span>,<span class="fl">3.2</span>,<span class="fl">2.4</span>,<span class="fl">1.5</span>,<span class="fl">2.8</span>,<span class="fl">1.1</span>,<span class="fl">1.7</span>,<span class="sc">-</span><span class="fl">1.5</span>,<span class="fl">2.2</span>,<span class="fl">0.4</span>,<span class="fl">0.6</span>,<span class="fl">2.9</span>,<span class="fl">2.3</span>,<span class="sc">-</span><span class="fl">0.2</span>,<span class="fl">3.3</span>,<span class="fl">0.7</span>,<span class="fl">3.1</span>,<span class="fl">1.9</span>,<span class="fl">1.7</span>,<span class="sc">-</span><span class="fl">0.5</span>,<span class="fl">1.1</span>,<span class="fl">4.4</span>)</span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>zoi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">69.2</span>,<span class="fl">68.6</span>,<span class="fl">74.7</span>,<span class="dv">73</span>,<span class="fl">45.9</span>,<span class="fl">57.7</span>,<span class="dv">64</span>,<span class="fl">50.1</span>,<span class="fl">66.7</span>,<span class="fl">66.4</span>,<span class="fl">67.1</span>,<span class="fl">63.9</span>,<span class="dv">73</span>,<span class="dv">75</span>,<span class="fl">62.4</span>,<span class="dv">67</span>,<span class="fl">74.2</span>,<span class="dv">45</span>,<span class="fl">74.4</span>,<span class="fl">60.6</span>,<span class="fl">55.2</span>,<span class="fl">64.1</span>,<span class="fl">66.6</span>,<span class="fl">72.5</span>,<span class="fl">52.4</span>)</span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>pbth <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">24</span>,<span class="dv">7</span>,<span class="dv">7</span>,<span class="dv">86</span>,<span class="dv">75</span>,<span class="dv">58</span>,<span class="dv">116</span>,<span class="dv">44</span>,<span class="dv">37</span>,<span class="dv">9</span>,<span class="dv">46</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">48</span>,<span class="dv">36</span>,<span class="dv">8</span>,<span class="dv">143</span>,<span class="dv">7</span>,<span class="dv">91</span>,<span class="dv">68</span>,<span class="dv">64</span>,<span class="dv">23</span>,<span class="dv">9</span>,<span class="dv">67</span>)</span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>spg <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.9</span>,<span class="fl">2.8</span>,<span class="fl">1.9</span>,<span class="fl">1.5</span>,<span class="fl">7.1</span>,<span class="fl">4.8</span>,<span class="fl">2.9</span>,<span class="fl">5.3</span>,<span class="dv">2</span>,<span class="fl">2.7</span>,<span class="fl">1.7</span>,<span class="dv">4</span>,<span class="fl">1.7</span>,<span class="fl">1.4</span>,<span class="fl">5.4</span>,<span class="dv">5</span>,<span class="fl">1.3</span>,<span class="fl">7.2</span>,<span class="fl">1.6</span>,<span class="fl">6.2</span>,<span class="fl">5.1</span>,<span class="fl">3.4</span>,<span class="fl">1.5</span>,<span class="fl">2.1</span>,<span class="dv">5</span>)</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a>aep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">659.91</span>,<span class="fl">4343.04</span>,<span class="fl">17529.98</span>,<span class="fl">20561.88</span>,<span class="fl">398.21</span>,<span class="fl">812.19</span>,<span class="fl">3219.22</span>,<span class="fl">97.39</span>,<span class="fl">341.31</span>,<span class="fl">1246.87</span>,<span class="fl">5400.66</span>,<span class="fl">988.58</span>,<span class="fl">21076.77</span>,<span class="fl">6501.23</span>,<span class="fl">831.81</span>,<span class="fl">9129.34</span>,<span class="fl">19204.92</span>,<span class="fl">229.01</span>,<span class="fl">18961.9</span>,<span class="fl">385.59</span>,<span class="fl">839.03</span>,<span class="fl">1674.15</span>,<span class="fl">1647.97</span>,<span class="fl">21965.08</span>,<span class="fl">686.75</span>)</span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>deimografikoiDeiktes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">XORA=</span>xora, <span class="at">ayxisi=</span>ayxisi, <span class="at">Zoi=</span>zoi, <span class="at">PBTH=</span>pbth, <span class="at">SPG=</span>spg, <span class="at">AEP=</span>aep)</span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(vegan)){</span>
<span id="cb17-9"><a href="#cb17-9" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;vegan&quot;</span>)</span>
<span id="cb17-10"><a href="#cb17-10" tabindex="-1"></a>  <span class="fu">library</span>(vegan)</span>
<span id="cb17-11"><a href="#cb17-11" tabindex="-1"></a>}</span>
<span id="cb17-12"><a href="#cb17-12" tabindex="-1"></a>eyresiDiastasis <span class="ot">&lt;-</span> <span class="cf">function</span>(dedomena, <span class="at">entasi =</span> <span class="fl">0.05</span>, <span class="at">ar_epan=</span><span class="dv">500</span>, <span class="at">metriki =</span> <span class="st">&quot;euclidean&quot;</span>){</span>
<span id="cb17-13"><a href="#cb17-13" tabindex="-1"></a>  dedomenaS <span class="ot">&lt;-</span> <span class="fu">scale</span>(dedomena[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb17-14"><a href="#cb17-14" tabindex="-1"></a>  dissimilarities <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(dedomenaS,metriki)</span>
<span id="cb17-15"><a href="#cb17-15" tabindex="-1"></a>  k0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb17-16"><a href="#cb17-16" tabindex="-1"></a>  nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb17-17"><a href="#cb17-17" tabindex="-1"></a>  stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb17-18"><a href="#cb17-18" tabindex="-1"></a>  <span class="cf">while</span> (k0 <span class="sc">&lt;</span> <span class="fu">length</span>(deimografikoiDeiktes[<span class="dv">1</span>,]) <span class="sc">&amp;&amp;</span> entasi<span class="sc">&lt;</span>stress0) {</span>
<span id="cb17-19"><a href="#cb17-19" tabindex="-1"></a>    k0 <span class="ot">&lt;-</span> k0<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb17-20"><a href="#cb17-20" tabindex="-1"></a>    nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb17-21"><a href="#cb17-21" tabindex="-1"></a>    stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb17-22"><a href="#cb17-22" tabindex="-1"></a>  }</span>
<span id="cb17-23"><a href="#cb17-23" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Η διάσταση είναι&quot;</span>,k0,<span class="st">&quot;και η ένταση είναι &quot;</span>,stress0,<span class="st">&quot;.&quot;</span>))</span>
<span id="cb17-24"><a href="#cb17-24" tabindex="-1"></a>  <span class="fu">stressplot</span>(nmds_result)</span>
<span id="cb17-25"><a href="#cb17-25" tabindex="-1"></a>}</span>
<span id="cb17-26"><a href="#cb17-26" tabindex="-1"></a><span class="fu">eyresiDiastasis</span>(deimografikoiDeiktes)</span>
<span id="cb17-27"><a href="#cb17-27" tabindex="-1"></a><span class="fu">eyresiDiastasis</span>(deimografikoiDeiktes, <span class="at">entasi=</span><span class="fl">0.02</span>)</span>
<span id="cb17-28"><a href="#cb17-28" tabindex="-1"></a>eyresiEntasis <span class="ot">&lt;-</span> <span class="cf">function</span>(dedomena, <span class="at">diastasi =</span> <span class="dv">2</span>, <span class="at">ar_epan=</span><span class="dv">500</span>, <span class="at">metriki =</span> <span class="st">&quot;euclidean&quot;</span>){</span>
<span id="cb17-29"><a href="#cb17-29" tabindex="-1"></a>  dedomenaS <span class="ot">&lt;-</span> <span class="fu">scale</span>(dedomena[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb17-30"><a href="#cb17-30" tabindex="-1"></a>  dissimilarities <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(dedomenaS,metriki)</span>
<span id="cb17-31"><a href="#cb17-31" tabindex="-1"></a>  k0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb17-32"><a href="#cb17-32" tabindex="-1"></a>  nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb17-33"><a href="#cb17-33" tabindex="-1"></a>  stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb17-34"><a href="#cb17-34" tabindex="-1"></a>  <span class="cf">while</span> (k0 <span class="sc">&lt;</span> <span class="fu">min</span>(diastasi,<span class="fu">length</span>(deimografikoiDeiktes[<span class="dv">1</span>,]))) {</span>
<span id="cb17-35"><a href="#cb17-35" tabindex="-1"></a>    k0 <span class="ot">&lt;-</span> k0<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb17-36"><a href="#cb17-36" tabindex="-1"></a>    nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> k0, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb17-37"><a href="#cb17-37" tabindex="-1"></a>    stress0 <span class="ot">&lt;-</span> nmds_result<span class="sc">$</span>stress</span>
<span id="cb17-38"><a href="#cb17-38" tabindex="-1"></a>  }</span>
<span id="cb17-39"><a href="#cb17-39" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Η διάσταση είναι&quot;</span>,k0,<span class="st">&quot;και η ένταση είναι &quot;</span>,stress0,<span class="st">&quot;.&quot;</span>))</span>
<span id="cb17-40"><a href="#cb17-40" tabindex="-1"></a>  <span class="fu">stressplot</span>(nmds_result)</span>
<span id="cb17-41"><a href="#cb17-41" tabindex="-1"></a>}</span>
<span id="cb17-42"><a href="#cb17-42" tabindex="-1"></a><span class="fu">eyresiEntasis</span>(deimografikoiDeiktes)</span>
<span id="cb17-43"><a href="#cb17-43" tabindex="-1"></a><span class="fu">eyresiEntasis</span>(deimografikoiDeiktes, <span class="at">diastasi =</span> <span class="dv">1</span>)</span>
<span id="cb17-44"><a href="#cb17-44" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(vegan3d)){</span>
<span id="cb17-45"><a href="#cb17-45" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;vegan3d&quot;</span>)</span>
<span id="cb17-46"><a href="#cb17-46" tabindex="-1"></a>  <span class="fu">library</span>(vegan3d)</span>
<span id="cb17-47"><a href="#cb17-47" tabindex="-1"></a>}</span>
<span id="cb17-48"><a href="#cb17-48" tabindex="-1"></a>PoPrKlim <span class="ot">&lt;-</span> <span class="cf">function</span>(dedomena, <span class="at">diastasi =</span> <span class="dv">2</span>, <span class="at">ar_epan=</span><span class="dv">500</span>, <span class="at">metriki =</span> <span class="st">&quot;euclidean&quot;</span>){</span>
<span id="cb17-49"><a href="#cb17-49" tabindex="-1"></a>  dedomenaS <span class="ot">&lt;-</span> <span class="fu">scale</span>(dedomena[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb17-50"><a href="#cb17-50" tabindex="-1"></a>  dissimilarities <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(dedomenaS,metriki)</span>
<span id="cb17-51"><a href="#cb17-51" tabindex="-1"></a>  nmds_result <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(dissimilarities, <span class="at">k =</span> diastasi, <span class="at">trymax=</span>ar_epan, <span class="at">trace=</span><span class="cn">FALSE</span>)</span>
<span id="cb17-52"><a href="#cb17-52" tabindex="-1"></a>  <span class="cf">if</span> (diastasi <span class="sc">==</span> <span class="dv">2</span>){</span>
<span id="cb17-53"><a href="#cb17-53" tabindex="-1"></a>  <span class="fu">ordiplot</span>(nmds_result, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb17-54"><a href="#cb17-54" tabindex="-1"></a>  <span class="fu">points</span>(nmds_result<span class="sc">$</span>points, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>)</span>
<span id="cb17-55"><a href="#cb17-55" tabindex="-1"></a>  <span class="fu">text</span>(nmds_result<span class="sc">$</span>points, <span class="at">labels =</span> dedomena[,<span class="dv">1</span>], <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb17-56"><a href="#cb17-56" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (diastasi <span class="sc">==</span> <span class="dv">3</span>) {</span>
<span id="cb17-57"><a href="#cb17-57" tabindex="-1"></a>    <span class="fu">ordiplot3d</span>(nmds_result, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb17-58"><a href="#cb17-58" tabindex="-1"></a>    <span class="fu">points</span>(nmds_result<span class="sc">$</span>points, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>)</span>
<span id="cb17-59"><a href="#cb17-59" tabindex="-1"></a>    <span class="fu">text</span>(nmds_result<span class="sc">$</span>points, <span class="at">labels =</span> dedomena[,<span class="dv">1</span>], <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb17-60"><a href="#cb17-60" tabindex="-1"></a>  }</span>
<span id="cb17-61"><a href="#cb17-61" tabindex="-1"></a>}</span>
<span id="cb17-62"><a href="#cb17-62" tabindex="-1"></a><span class="fu">PoPrKlim</span>(deimografikoiDeiktes)</span>
<span id="cb17-63"><a href="#cb17-63" tabindex="-1"></a><span class="fu">PoPrKlim</span>(deimografikoiDeiktes, <span class="at">diastasi =</span> <span class="dv">3</span>)</span></code></pre></div>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p>Σε ό,τι ακολουθεί η απόσταση που χρησιμοποιείται είναι η
ευκλείδεια. Ο αναγνώστης, όμως, μπορεί να επιλέξει κάποια άλλη, όπως θα
δούμε παρακάτω.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
