on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch: {}

name: demo-r-shinylive-app

jobs:
  demo-website:
    runs-on: ubuntu-latest
    concurrency:
      group: r-shinylive-website-${{ github.event_name != 'pull_request' || github.run_id }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2

      - name: "Setup R dependency for Shinylive App export"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            cran::shinylive@0.1.1

      - name: Create Shinylive App from working directory files
        shell: Rscript {0}
        run: |
          shinylive::export(".", "_site")

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3  # Αναβάθμιση σε v3 αν υπάρχει
        with: 
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3  # Αναβάθμιση σε v3 αν υπάρχει
